config/routes.rb
Rails.application.routes.draw do
   get 'home/index' 
   root 'home#index'
   
  get '/home/alluser' => 'home#alluser'
  get '/home/notification' => 'home#notification'
  post '/follow' => 'home#follow'
   devise_for :users, :controllers => { registrations: 'registrations' }
   resources :posts
   post 'likes/like'
   post '/home/notification' => 'home#notification'
   get '/profile/index' => 'profile#index'
   get '/profile/popup' => 'profile#popup'
   post 'comments/comment'
   

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	  before_action :authenticate_user!

	def index
		celebs = Followmapping.where(follower_id: current_user.id).pluck(:celeb_id)
		celebs[celebs.length] = current_user.id
		@posts=Post.where(user_id: celebs)
    @posts.order! 'created_at DESC'
    @post = Post.new
    
  end

	def alluser
		@users = User.all
    @post = Post.new
  
	end

	def follow
  	celeb_id = params[:celeb_id]
    @can_follow = false
    @can_unfollow = false
    @user = celeb_id
  	if current_user.can_follow celeb_id
  		Followmapping.create(:celeb_id => celeb_id, :follower_id => current_user.id)
      @can_follow = true
  	elsif current_user.can_un_follow celeb_id
      @can_unfollow = true
      Followmapping.where(:celeb_id => celeb_id, :follower_id => current_user.id).first.destroy
  	end
     respond_to do |format|
      format.html { redirect_to '/home/alluser' }
      format.js {}
      format.json{}
      end
  	 # return redirect_to '/home/alluser'
  end

  def notification
    posts = Post.where(user_id: current_user.id).pluck(:id)
    @notifications = Like.where(post_id: posts)
    @notifications += Comment.where(post_id: posts)
    @notifications += Followmapping.where(celeb_id: current_user.id)
    @notifications.sort_by! &:created_at
    @notifications.reverse!
    notification = Notification.where(user_id: current_user.id).first
    if notification.nil?
        Notification.create(user_id: current_user.id)
    else
        if notification.created_at < @notifications.first.created_at
              notification.destroy  
        else  
              notification.destroy  
              Notification.create(user_id: current_user.id)
        end
    end
    respond_to do |format|
      format.html{redirect_to '/home/index'}
      format.js{}
    end
  end

 
  # def un_follow
  # 	celeb_id = params[:celeb_id]
  #    @can_follow = false
  #   @user = celeb_id
  # 	if current_user.can_un_follow celeb_id
  #     @can_follow = true
  # 		Followmapping.where(:celeb_id => celeb_id, :follower_id => current_user.id).first.destroy
  # 	else
  # 	end
  #     respond_to do |format|
  #     format.html { redirect_to '/home/alluser' }
  #     format.js {}
  #     format.json{}
  #     end
  #    # return redirect_to '/home/alluser'
  # end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_comment.html.erb
<div class="comments" id="comment_<%=post.id%>">
  <%(post.comments).each do |comment|%>
  <div class="comment-wrapper">
<div class="comment-user"><h3><%= link_to comment.user.username ,profile_index_path(comment.user.username),class: "noty-username" %></h3></div>          
 <div class="comment-content"><p><%=comment.content %></p></div>
  </div>
  <%end%>
</div>

<form action="/comments/comment" method="POST" data-remote="true">
   <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
<div class="comment-add" style="height: 14px;">
	<textarea aria-label="Add a comment…" name="content" id="commentu_<%= post.id%>" class="_2hc0g" placeholder="Add a comment…" style="height: 18px;width: 90%" datapost="<%= post.id%>"></textarea>
</div>
<input type="hidden" name="postid" value="<%=post.id %>">
<input type="image" class="plus-button like-button" id="submit_<%= post.id%>" name="submit" src="/images/plus.png" border="0" alt="Like" />
</form>


<script type="text/javascript">
(function(){
var textarea = $("textarea[datapost='<%= post.id %>']");
textarea.on('keydown',function(event){
	if(event.key === 'Enter'){
		$('#submit_<%=post.id%>').trigger('click');
	}
});
})();
</script>

app/views/home/_commentpartial.html.erb
  <div class="comment-wrapper">
<div class="comment-user"><h3><%=(comment.user).username%></h3></div>          
 <div class="comment-content"><p><%=comment.content %></p></div>
  </div>

app/views/home/_like.html.erb
  <div class="like-comment-buttons" id="like_<%=post.id%>">
<div class="like-button"> 
<form action="/likes/like" method="POST" data-remote="true">
  <input type="hidden" name="post_id" value="<%=post.id %>">
  
     <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
   
  <% if current_user.likes.where(post_id:post.id).first %>
  <input type="hidden" name="value" value="liked">
   <input type="image" class="like-button" id="likedjs"  name="submit" src="/images/heartfilled.png" border="0" alt="UnLike" />
  <% else %>
    <input type="hidden" name="value" value="like">
  <input type="image" class="like-button likejs" id="likejs" name="submit" src="/images/heart.png" border="0" alt="Like" />
<% end %>
</form>
</div>
<div class="button-comment" ><img id="commu_<%=post.id%>" class="comment-button"src="/images/comment.png"></div>
<div class="like-counter"><h3><%=post.likes.length%> likes</h3></div>

</div>
<script type="text/javascript">


var commentbutton = $("#commu_<%=post.id%>");
commentbutton.on('click',function(event){
	   
		$('#commentu_<%=post.id%>').focus();
	
});

</script>

app/views/home/_notification.html.erb
<% if not notifications.nil?%>
  <% notifications.each do |notification|%>


<% unless notification.class==Followmapping%>
<div class="noty">
<div class="noty-text-wrapper">
<div class="user-pic noty-pic">
		<%= image_tag(notification.user.avatar.url(:thumb),:class =>"post-user-profile-pic",:style=>"margin-left:10px;") %>
		</div>
<div class="noty-username">
<h3><%= link_to notification.user.username ,profile_index_path(notification.user.username),class: "noty-username" %></h3>
	</div>
	<div class="noty-type">
		<%if notification.class == Like%><h4><p>liked your Post</p></h4><%end%>
		<%if notification.class == Comment%><h4><p>commmented: <%=notification.content%></p></h4><%end%>

	</div> 
</div>
<%=image_tag(notification.post.image.url(:thumb),:class=>"noty-image")%>
</div>
<%else%>
<div class="noty1">
<div class="noty1_1">
<div class="user-pic noty-pic">
<%user=User.where(id:notification.follower_id).first%>
		<%= image_tag(user.avatar.url(:thumb),:class =>"post-user-profile-pic",:style=>"margin-left:10px;") %>
		</div>
<div class="noty-username">
<h3><%=link_to user.username ,profile_index_path(user.username),class: "noty-username" %></h3>
	</div>
	<div class="noty-type">
		<p>started following you.</p></div>
</div>
		<%= link_to image_tag("#{current_user.follow_button user.id}"), url_for(controller: :home, action: :follow, celeb_id: user.id), method: :post ,remote: true , id: "follow_#{user.id}",class:"noty-follow-button"%>
	</div> 
<% end %>
<%end%>

<%else%>
<h4>Nothing to show,kid!!!</h4>
    <%end%>
    

app/views/home/_post.html.erb
      <div class="post-header">
	<div class="user-pic">
	<%= image_tag(post.user.avatar.url(:thumb),:class =>"post-user-profile-pic") %>
		</div>
		<div class="user-name"><h3><%= link_to post.user.username ,profile_index_path(post.user.username),class: "user-name" %></h3></div>
	</div>
        <div class="post-image" id="post-image-<%=post.id%>"><%=image_tag post.image.url(:medium)%></div>
        <div class="comment-wrapper">
	<div class="comment-user"><h3><%= link_to post.user.username ,profile_index_path(post.user.username),class: "noty-username" %></h3></div>
     <div class="comment-content"><p><%= post.content %></p></div>
</div>



<form action="/likes/like" method="POST" data-remote="true" id="like-form-on-double-<%=post.id%>">
  <input type="hidden" name="post_id" value="<%=post.id %>">
  
     <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
   
  <% if current_user.likes.where(post_id:post.id).first %>
  <input type="hidden" name="value" value="liked">
   
  <% else %>
    <input type="hidden" name="value" value="like">
<% end %>
</form>

<script type="text/javascript">
	$("#post-image-<%=post.id%>").dblclick(function(){
		$("#like-form-on-double-<%=post.id%>").submit();
	});
</script>

app/views/home/adddp.html.erb
<%= form_for @user,html: { multipart: true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>

app/views/home/alluser.html.erb
<!-- header starts here -->

<link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
	<%= content_for(:title,"Instagram")%>
<div class="header">
<div class="header-wrapper">
<div class="logos">
	<div class="homelogo-div" ><%=link_to (image_tag('/images/homelogo.png',:class =>"homelogo")),
	home_index_path  %></div>
	<div class="header-partition-line"></div>
	<div class="download-div" ><%=link_to (image_tag('/images/download.png',:class =>"download")),home_index_path %></div>
</div>
<div class="search-bar">
	<input type="text" class="top-search" placeholder="&#xf002;  Search" value="">
</div>

<div class="links">
	<div class="users"><%= link_to(image_tag('/images/compass-icon.png',:class=>"links-top-icon"),home_alluser_path,class: "users") %></div>
	<div class="profile"><%= link_to( image_tag('/images/user-icon.png',:class=>"links-top-icon"),profile_index_path(current_user.username),class: "profile") %></div>
<div class="notifications w3-dropdown-click"><%= link_to( image_tag('/images/heart.png',:class=>"links-top-icon"),url_for(controller: :home , action: :notification),class: "newpost",remote: true,id: "myBtn")%>
<div class="hidden-red-dot_<%=current_user.has_notifications%>" id="top-notification-dot"></div>
    <div id="all-notifications" class="w3-dropdown-content w3-animate-zoom" style="display: none;">
    <span class="close">&times;</span>
    </div>
  </div>

</div>

</div>
</div>


<!-- header ends here -->
<div class="all_user_outer_container">
<% @users.each do |user| %>
<%unless user.id == current_user.id%>
		<div class="all_users_container">
			<div class="all-user-name-wrapper">
			<div class="all_user_profile_image">
			<%= image_tag(user.avatar.url(:medium),:class =>"profile-pic") %>
			</div>
			<div class="all_user_username">
			<h3><%= link_to user.username ,profile_index_path(user.username),class: "user-name1" %></h3>
			<div class="all_user_fullname"><%= user.fullname%></div>
			</div>
			</div>
				
			
			<div class="all_user_follow_button">
				 
				<%= link_to image_tag("#{current_user.follow_button user.id}"), url_for(controller: :home, action: :follow, celeb_id: user.id), method: :post ,remote: true , id: "follow_#{user.id}"%>
				
			</div>
		</div>
<% end %>
<% end %>
<div>
<div id="newpost-icon"><%= image_tag("/images/newpost.png",:class=>"newpost1")%></div>
<div class="newpost-popup"><%=render 'posts/newpost'%></div>
<style type="text/css">
	.all-user-name-wrapper{
		display: flex;
		flex-direction: row;
	}
	.all_user_outer_container{
		display: flex;
		padding-top: 120px;
		flex-direction: column;
		align-items: center;
	}
	.all_users_container{
		display: flex;
		justify-content: space-between;
		padding: 10px;
		height:80px;
		width: 600px;
		flex-direction: row;
		border-left: 1px solid;
		border-right: 1px solid;
		border-top: 0.5px solid;
		border-bottom: 0.5px solid;
		border-color: #efefef;
		
	}
	.profile-pic{
		width: 100%;
		height:100%;
	}
	.all_user_profile_image{
		margin-left:5px;
		margin-right: 10px; 
		height: 60px;
		width:60px;
		border-radius: 60px;
		background-color: blue;
	}
	.all_user_follow_button{
		
	}
	.all_user_username{
		color: #262626;
		font-size: 14px;
    	font-weight: 600;
    	line-height: 10px;
	}
	.all_user_fullname{
		    color: #999;
		    font-size: 14px;
    		font-weight: 400;
    		margin-left: 15px;
	}
	.user-name1{
		margin-top: 10px;
		margin-left: 15px;
		color: black;
    	text-decoration: none;
	}
</style>
<script type="text/javascript">
;(function($) {
        $(function() {
            $('#newpost-icon').bind('click', function(e) {
                e.preventDefault();
                $('.newpost-popup').bPopup();

            });

        });

    })(jQuery);
  var modal = document.getElementById('all-notifications');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target != modal) {
        modal.style.display = "none";
    }

}
$("#myBtn").click(function(){
    console.log("hello");
    $("#top-notification-dot").css("display","none");
});

</script>

app/views/home/follow.js.erb
 <%if @can_follow %>
 	
 	 console.log("follow_<%=@user%>");
 	 $("#follow_<%=@user%>").html("<img src='/images/following.png'>")
 	
 <%end%>
<% if @can_unfollow %>

	console.log("unfollow_<%=@user%>");	
	$("#follow_<%=@user%>").html("<img src='/images/follow.png'>");

<%end%>

app/views/home/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	<%= content_for(:title,"Instagram")%>

<div class="header">
<div class="header-wrapper">
<div class="logos">
	<div class="homelogo-div" ><%= image_tag('/images/homelogo.png',:class =>"homelogo")  %></div>
  <div class="header-partition-line"></div>
	<div class="download-div" ><%= image_tag('/images/download.png',:class =>"download")  %></div>
</div>
<div class="search-bar">
	<input type="text" class="top-search" placeholder="&#xf002;  Search" value="">
</div>

<div class="links">
  <div class="users"><%= link_to(image_tag('/images/compass-icon.png',:class=>"links-top-icon"),home_alluser_path,class: "users") %></div>
  <div class="profile"><%= link_to( image_tag('/images/user-icon.png',:class=>"links-top-icon"),profile_index_path(current_user.username),class: "profile") %></div>
<div class="notifications w3-dropdown-click"><%= link_to( image_tag('/images/heart.png',:class=>"links-top-icon"),url_for(controller: :home , action: :notification),class: "newpost",remote: true,id: "myBtn")%>
<div class="hidden-red-dot_<%=current_user.has_notifications%>" id="top-notification-dot"></div>
    <div id="all-notifications" class="w3-dropdown-content w3-animate-zoom" style="display: none;">
    <span class="close">&times;</span>
    </div>
  </div>

</div>


</div>
</div>








<div class="posts">
 <% @posts.each do |post| %>
<div class="post">
 
 <%=render 'post',post:post%>
 <%=render 'like',post:post%>
 <%=render 'comment',post:post%>
</div>
<%end%>
      </div>
<div id="newpost-icon"><%= image_tag("/images/newpost.png",:class=>"newpost1")%></div>
<div class="newpost-popup"><%=render 'posts/newpost'%></div>
<script type="text/javascript">
  
  ;(function($) {
        $(function() {
            $('#newpost-icon').bind('click', function(e) {
                e.preventDefault();
                $('.newpost-popup').bPopup();

            });

        });

    })(jQuery);

 var modal = document.getElementById('all-notifications');

var btn = document.getElementById("myBtn");

var span = document.getElementsByClassName("close")[0];

btn.onclick = function() {
    modal.style.display = "block";
}
span.onclick = function() {
    modal.style.display = "none";
}
window.onclick = function(event) {
    if (event.target != modal) {
        modal.style.display = "none";
    }

}
$("#myBtn").click(function(){
    console.log("hello");
    $("#top-notification-dot").css("display","none");
});
</script>

app/views/home/notification.js.erb
$("#all-notifications").html("<%= escape_javascript render 'notification' ,notifications: @notifications %>");